services:
    db:
        image: postgres:16-alpine
        container_name: affluencepath
        env_file:
            - .env.dev
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
        volumes:
            - ./docker/volumes/pgdata:/var/lib/postgresql/data
